---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: argocd
  namespace: tanzu-package-repo-global
  annotations:
    kapp.k14s.io/change-rule.service-account: delete before deleting platform-sa
spec:
  serviceAccountName: platform-sa
  packageRef:
    refName: argocd.neptunus.thomasvitale.com
    versionSelection:
      constraints: 2.4.0
      prereleases: {}
