---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cartographer-catalog
  namespace: tanzu-package-repo-global
  annotations:
    kapp.k14s.io/change-rule.app-toolkit: upsert after upserting app-toolkit
    kapp.k14s.io/change-rule.argocd: upsert after upserting argocd
    kapp.k14s.io/change-rule.tekton: upsert after upserting tekton
    kapp.k14s.io/change-rule.service-account: delete before deleting platform-sa
spec:
  serviceAccountName: platform-sa
  packageRef:
    refName: cartographer-catalog.neptunus.thomasvitale.com
    versionSelection:
      constraints: 0.1.0
      prereleases: {}
  values:
  - secretRef:
      name: cartographer-catalog-values

---
apiVersion: v1
kind: Secret
metadata:
  name: cartographer-catalog-values
  namespace: tanzu-package-repo-global
stringData:
  values.yml: |
    ---
    registry:
      server: ghcr.io
      repository: thomasvitale/goto
      
