---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: supply-chain-workload
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: supply-chain-workload
subjects:
  - kind: ServiceAccount
    name: default