---
apiVersion: v1
kind: Namespace
metadata:
  name: staging

---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: staging
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: staging
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
secrets:
- name: registry-credentials
imagePullSecrets:
- name: registry-credentials

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: supply-chain-workload
  namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: supply-chain-workload
subjects:
  - kind: ServiceAccount
    name: default
