---
apiVersion: v1
kind: Namespace
metadata:
  name: test

---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: test
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-user-sa
  namespace: test
secrets:
- name: registry-credentials
imagePullSecrets:
- name: registry-credentials