---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tekton-pipelines
  namespace: tanzu-package-repo-global
  annotations:
    kapp.k14s.io/change-group: tekton-pipelines
    kapp.k14s.io/change-rule.service-account: delete before deleting platform-sa
spec:
  serviceAccountName: platform-sa
  packageRef:
    refName: tekton-pipelines.neptunus.thomasvitale.com
    versionSelection:
      constraints: 0.36.0
      prereleases: {}
