---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-testing-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: testing-role
subjects:
  - kind: ServiceAccount
    name: testing-sc-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testing-role
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - tasks
      - taskruns
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - get

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testing-sc-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workload-role
subjects:
  - kind: ServiceAccount
    name: testing-sc-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workload-role
rules:
  - apiGroups:
      - source.toolkit.fluxcd.io
      - kpack.io
      - kapp.k14s.io/v1alpha1
      - kappctrl.k14s.io
      - serving.knative.dev/v1
      - carto.run
    resources:
      - gitrepositories
      - images
      - configs
      - apps
      - services
      - runnables
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - get
