SOURCE_IMAGE = os.getenv("SOURCE_IMAGE", default='ghcr.io/thomasvitale/goto/music-service-source')
LOCAL_PATH = os.getenv("LOCAL_PATH", default='.')
NAMESPACE = os.getenv("NAMESPACE", default='default')

k8s_custom_deploy(
    'music-service',
    apply_cmd="tanzu apps workload apply -f config/workload.yml --live-update" +
               " --local-path " + LOCAL_PATH +
               " --source-image " + SOURCE_IMAGE +
               " --namespace " + NAMESPACE +
               " --yes >/dev/null" +
               " && kubectl get workload music-service --namespace " + NAMESPACE + " -o yaml",
    delete_cmd="tanzu apps workload delete -f config/workload.yml --namespace " + NAMESPACE + " --yes",
    deps=['build.gradle', './build/classes'],
    container_selector='workload',
    live_update=[
      sync('./build/classes', '/workspace/BOOT-INF/classes')
    ]
)

k8s_resource('music-service', port_forwards=["8080:8080"],
            extra_pod_selectors=[{'serving.knative.dev/service': 'music-service'}])
