---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tkg-repo
  namespace: tanzu-package-repo-global
  annotations:
    kapp.k14s.io/change-group: package-repo
spec:
  syncPeriod: 1m
  fetch:
    imgpkgBundle:
      image: projects.registry.vmware.com/tce/repo-12:0.12.0
