---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: secretgen-controller
  namespace: tanzu-package-repo-global
  annotations:
    kapp.k14s.io/change-rule.service-account: delete before deleting platform-sa
    kapp.k14s.io/change-rule.package-repo: upsert after upserting package-repo
spec:
  serviceAccountName: platform-sa
  packageRef:
    refName: secretgen-controller.community.tanzu.vmware.com
    versionSelection:
      constraints: 0.7.1
      prereleases: {}
